name: pyscf
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python
  - anaconda
  - numpy
  - scipy
  - pandas
  - pyscf==2.7.0
  - opt_einsum
  - scikit-learn
  - basis_set_exchange
  - wandb
  - tqdm
  - pip
  - pip:
    - segmentation_models_pytorch==0.3.3