name: pyscf_ml
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python>=3.10
  - anaconda
  - numpy
  - scipy
  - pandas
  - pyscf
  - opt_einsum
  - scikit-learn
  - basis_set_exchange
  - wandb
  - tqdm
